@node The command line
@chapter The command line

The command line is the most powerful
way to interact with the computer, and
it generally is also the fastest way
to perform actions. But it requires
some knowledge to take full advantage
of it. In this chapter you will learn
how to use the command line in less
basic ways.


@menu
* The command line advantage::
@end menu



@node The command line advantage
@section The command line advantage

@cindex flexibility
@cindex unix-pipes
@cindex pipes
The command line is extremely flexible.
In GNU and all Unix-like systems
command line problems are designed to
to just one thing and be very good at
it. This by itself does not make the
the command line great, rather it makes
it cumbersome to use, but shells in
Unix-like systems — the program that
lets you use the command line — implement
a concept called Unix-pipes. Unix-pipes
is a way to combine programs. This two
designs combine makes the command line
virtually unlimited in its flexibility.

@cindex reliability
Graphical programs are often immature
and even unstable. In contrast, command
line tools are most often highly
reliable.

