@node Usage basics
@chapter Usage basics

@menu
* Virtual terminals::
* Shells::
* Text editors::
@end menu


@node Virtual terminals
@section Virtual terminals

@cindex switch terminal
@cindex terminals, switch
@cindex TTY
@cindex teletypewriter
@cindex virtual terminal
@cindex terminal
By default no graphical environment is
installed, which means that you will
only have a basic terminal. However,
you can switch between terminals by
pressing @kbd{Alt+Left} and @kbd{Alt+Right}.
The terminals are index @file{tty1}
though @file{tty63} (all are not
available by default), pressing
@kbd{Alt+F4}, for example, will switch
directly to @file{tty4}. These terminals
of often called TTY:s (teletypewriters).



@node Shells
@section Shells

@cindex shell
@cindex terminal
When you log in on a terminal, or
open a new terminal in a graphical
session, a shell is opened. This is
program that lets you start other
program and perform actions using
script shell language. To start a
program you simply name it in the
most basic cases.

@pindex GNU Bash
@pindex @command{bash}
@pindex @command{chsh}
@cindex shell, change default
The default shell is GNU Bash, or
simply @command{bash}, if you want
to change it you can use the command
@command{chsh}.

@cindex @file{.bashrc}
@cindex @file{~/.bashrc}
@cindex shell, configure
@pindex bash.d
Must shells uses a script file in the
user's home directory to configure,
which includes how the shell looks.
The file is a dotfile (the filename
starts with a dot) with means it is
hidden. GNU Bash uses the file
@file{.bashrc}, which generally is
called @file{~/.bashrc}, @file{~/}
means that it is located in your
home directory. You can use the
package `bash.d' to configure your
GNU Bash shell, it is a collection
of files that can be included in
your @file{~/.bashrc} file.

@cindex shell, stop
@cindex shell, terminal
@cindex shell, close
To stop a program in the shell press
@kbd{Ctrl+c}. There are a few programs
that disables this which means that
you need to learn how to close those
programs individually.

@cindex shell, logout
You can close a shell by typing
@command{exit}, or in some shells
@command{logout}. If you have not
typed anything since the last time
you pressed enter, you can also
press @kbd{Ctrl+d}. Closing the
login shell means that you logout.
The login shell is the first shell
that is opened when you log in if
you have logged in on a terminal.

@cindex shell, pause
@cindex shell, suspend
@cindex shell, resume
You can also suspend a program
by pressing @kbd{Ctrl+z}. which
means that the program will be
completely paused and you are
returned to the shell. Typing
@command{%} or @command{fg}
resumes the last suspended
program.



@node Text editors
@section Text editors

@cindex text editor
@cindex editor, text
@pindex GNU Nano
@pindex @command{nano}
To edit configurations, and write
files in general, you need a text
editor. The simplest is called GNU
Nano, often just called Nano,
which is started with the command
@command{nano} followed by the file
you want to edit or create.

@pindex GNU Emacs
@pindex @command{emacs}
@pindex @command{emacs -nw}
@opindex @option{-nw}, Emacs
A powerful alternative is GNU Emacs,
often just called Emacs, which is
started with the command @command{emacs}
instead of Nano's @command{nano}, or
@command{emacs -nw} if you want to
start it in the terminal and are
using a graphical environment. Learning
GNU Emacs, or another powerful, editor
will save you time (and mental sanity)
in the long run. Choosing Emacs means
that you will learn keyboard commands
similar to those of the shell. Emacs
is exited with the key combination
@kbd{C-x, C-c} with stands for
@kbd{Ctrl+x} followed by @kbd{Ctrl+c}.

